site_name: Unity VR and Eye Tracking Workshop
nav:
  - Welcome: index.md
  - 1 • First Unity Project: 1-first-project.md
  - 2 • Interaction in VR: 2-vr-interaction.md
  - 3 • Runtime: 3-runtime.md
  - 4 • Coroutines: 4-coroutines.md
  - 5 • Saving, Loading, Writing: 5-io.md
  - 6 • Using Gaze Data: 6-gaze.md
  - 7 • Final Challenge: 7-challenge.md
  - Installation and Setup: page-0.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - attr_list
  - md_in_html

theme:
  features:
    - navigation.tracking
    # - navigation.instant
    # - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    # - navigation.top
    - header.autohide
  name: material
  font:
    text: Source Sans Pro
    code: Source Code Pro
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to bright mode

  logo: assets/sfb-x.png
  favicon: assets/favicon.png
