site_name: VR and Eye Tracking Workshop
nav:
  - Welcome: index.md
  - Get Going: page-1.md
theme:
  features:
    - navigation.tracking
    - navigation.instant
    # - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top
    - header.autohide
  name: material
  font:
    text: Source Sans 3
    code: Source Code Pro
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to bright mode

  logo: assets/sfb-x.png
